---
language: php

addons:
  apt:
    packages:
    - elinks # For dysplaying php files on console.
    # - colordiff

cache:
  directories:
  - $HOME/.composer/cache/files

php:
- nightly
- 7.2
- 7.1
- 7.0

# env:
  # global:
  # - COMPOSER_BIN_DIR=bin
  # - COMPOSER=composer-dev.json # https://travis-ci.org/symfony-flex-demo/env-COMPOSER-and-symfony.lock
  # - PATH=$TRAVIS_BUILD_DIR/bin::$PATH

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

before_install:
- go get -u github.com/jingweno/ccat
# Disabling Xdebug - Debugger and Profiler Tool for PHP
- |
  php -r "print_r(get_loaded_extensions(TRUE));"
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    install --directory ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand
    mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand
    php -r "print_r(get_loaded_extensions(TRUE));"
  fi
install:
- |
  # mv composer.json composer-orig.json
  # mv composer-skeleton.json composer.json
  # composer --no-install create-project -vvv --no-scripts --no-plugins --no-install symfony/skeleton
  git clone https://github.com/symfony/skeleton.git
  cd skeleton
  composer config bin-dir bin
  composer update symfony/flex
  composer update symfony/yaml
  composer update symfony/dotenv # --dev
  composer update symfony/framework-bundle
  composer update symfony/console
  composer update

script:
- composer require --no-scripts sensiolabs/security-checker &> /dev/null && composer exec security-checker security:check -- --end-point=http://security.sensiolabs.org/check_lock --ansi
# - composer exec -- console --ansi
- composer exec console
- composer exec -vvv -- console

after_script:
- ls --almost-all --color
- cat .env
- cat .env.dist
- ls --color bin
- php -s bin/console | elinks -force-html -dump-color-mode 4 -dump
- ls --almost-all --recursive --color var
- ls --color src
- ls --recursive --color config


- composer show --latest
- $GOPATH/bin/ccat composer-orig.json
- $GOPATH/bin/ccat composer.json
# - diff --help
# - diff --minimal --side-by-side --color composer-dev.json composer.json needs a Ubuntu version newer than Trusty
# - colordiff --minimal --side-by-side composer-orig.json composer.json

- composer exec --list
- composer run-script --list

- composer exec -- console list debug --ansi
