---
language: php

addons:
  apt:
    packages:
    - elinks # For dysplaying php files on console.
    - colordiff

cache:
  directories:
  - $HOME/.composer/cache/files

php:
- nightly
- 7.2
- 7.1
- 7.0

env:
  global:
  - COMPOSER_BIN_DIR=bin
  # - COMPOSER=composer-dev.json # https://travis-ci.org/symfony-flex-demo/env-COMPOSER-and-symfony.lock
  # - PATH=$TRAVIS_BUILD_DIR/bin::$PATH

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

before_install:
- go get -u github.com/jingweno/ccat
# Disabling Xdebug - Debugger and Profiler Tool for PHP
- |
  php -r "print_r(get_loaded_extensions(TRUE));"
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    install --directory ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand
    mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand
    php -r "print_r(get_loaded_extensions(TRUE));"
  fi
install:
- |
  # mv composer.json composer-orig.json
  # mv composer-skeleton.json composer.json
  composer require symfony/flex
  composer require symfony/yaml
  # composer require symfony/dotenv --dev
  composer require symfony/console
